// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_sosfilt
List cpp_sosfilt(NumericMatrix sos, NumericVector x, NumericMatrix zi);
RcppExport SEXP _PhysioPreprocess_cpp_sosfilt(SEXP sosSEXP, SEXP xSEXP, SEXP ziSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sos(sosSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type zi(ziSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sosfilt(sos, x, zi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lfilter
List cpp_lfilter(NumericVector b, NumericVector a, NumericVector x, NumericVector zi);
RcppExport SEXP _PhysioPreprocess_cpp_lfilter(SEXP bSEXP, SEXP aSEXP, SEXP xSEXP, SEXP ziSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zi(ziSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lfilter(b, a, x, zi));
    return rcpp_result_gen;
END_RCPP
}
// cpp_filtfilt_ba
NumericVector cpp_filtfilt_ba(NumericVector b, NumericVector a, NumericVector x);
RcppExport SEXP _PhysioPreprocess_cpp_filtfilt_ba(SEXP bSEXP, SEXP aSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_filtfilt_ba(b, a, x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_filtfilt_ba_mat
NumericMatrix cpp_filtfilt_ba_mat(NumericVector b, NumericVector a, NumericMatrix x);
RcppExport SEXP _PhysioPreprocess_cpp_filtfilt_ba_mat(SEXP bSEXP, SEXP aSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_filtfilt_ba_mat(b, a, x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sosfiltfilt
NumericVector cpp_sosfiltfilt(NumericMatrix sos, NumericVector x, int nfact);
RcppExport SEXP _PhysioPreprocess_cpp_sosfiltfilt(SEXP sosSEXP, SEXP xSEXP, SEXP nfactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sos(sosSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nfact(nfactSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sosfiltfilt(sos, x, nfact));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sosfiltfilt_mat
NumericMatrix cpp_sosfiltfilt_mat(NumericMatrix sos, NumericMatrix x, int nfact);
RcppExport SEXP _PhysioPreprocess_cpp_sosfiltfilt_mat(SEXP sosSEXP, SEXP xSEXP, SEXP nfactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sos(sosSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nfact(nfactSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sosfiltfilt_mat(sos, x, nfact));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PhysioPreprocess_cpp_sosfilt", (DL_FUNC) &_PhysioPreprocess_cpp_sosfilt, 3},
    {"_PhysioPreprocess_cpp_lfilter", (DL_FUNC) &_PhysioPreprocess_cpp_lfilter, 4},
    {"_PhysioPreprocess_cpp_filtfilt_ba", (DL_FUNC) &_PhysioPreprocess_cpp_filtfilt_ba, 3},
    {"_PhysioPreprocess_cpp_filtfilt_ba_mat", (DL_FUNC) &_PhysioPreprocess_cpp_filtfilt_ba_mat, 3},
    {"_PhysioPreprocess_cpp_sosfiltfilt", (DL_FUNC) &_PhysioPreprocess_cpp_sosfiltfilt, 3},
    {"_PhysioPreprocess_cpp_sosfiltfilt_mat", (DL_FUNC) &_PhysioPreprocess_cpp_sosfiltfilt_mat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PhysioPreprocess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
