# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_sosfilt <- function(sos, x, zi) {
    .Call(`_PhysioPreprocess_cpp_sosfilt`, sos, x, zi)
}

cpp_lfilter <- function(b, a, x, zi) {
    .Call(`_PhysioPreprocess_cpp_lfilter`, b, a, x, zi)
}

cpp_filtfilt_ba <- function(b, a, x) {
    .Call(`_PhysioPreprocess_cpp_filtfilt_ba`, b, a, x)
}

cpp_filtfilt_ba_mat <- function(b, a, x) {
    .Call(`_PhysioPreprocess_cpp_filtfilt_ba_mat`, b, a, x)
}

cpp_sosfiltfilt <- function(sos, x, nfact) {
    .Call(`_PhysioPreprocess_cpp_sosfiltfilt`, sos, x, nfact)
}

cpp_sosfiltfilt_mat <- function(sos, x, nfact) {
    .Call(`_PhysioPreprocess_cpp_sosfiltfilt_mat`, sos, x, nfact)
}

